apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
      - image: ${project.artifactId}:latest
        name: ${project.artifactId}
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTIONS
          value: "-Dspring.profiles.active=openshift"
        - name: KAFKA_BOOTSTRAP_SERVER
          value: my-kafka-cluster
        - name: KAFKA_BOOTSTRAP_PORT
          value: 9092
